import './styles/theme.css';
import './styles/base.css';
import * as utils from 'cloud-ui.vusion/src/utils';
// import '../src/style/base.less'; // 下方有对src目录里所有less文件的引用

// import Vue from 'vue';
// Vue.prototype.$env = Vue.prototype.$env || {};
// Vue.prototype.$env.VUE_APP_DESIGNER = String(process.env.VUE_APP_DESIGNER) === 'true';

export { utils };
export { install } from '@vusion/utils';
export * from './components';

import Vue from 'vue';
Vue.prototype.$env = Vue.prototype.$env || {};
Vue.prototype.$env.VUE_APP_DESIGNER = String(process.env.VUE_APP_DESIGNER) === 'true';

import '../src/style/animation.less';
import '../src/style/base.less';
import '../src/style/clearfix.less';
import '../src/style/ellipsis.less';
import '../src/style/hairline.less';
import '../src/style/mixins/clearfix.less';
import '../src/style/mixins/ellipsis.less';
import '../src/style/mixins/hairline.less';
import '../src/style/normalize.less';
import '../src/style/reset.less';
import '../src/style/var.less';

import '../src/popup/index.less';
import '../src/overlay/index.less';

import '../src/action-sheet/index.less';
import '../src/address-edit/index.less';
import '../src/address-list/index.less';
import '../src/area/index.less';
import '../src/badge/index.less';
import '../src/button/index.less';
import '../src/calendar/index.less';
import '../src/capsules-group/index.less';
import '../src/capsules-item/index.less';
import '../src/capsules/index.less';
import '../src/card/index.less';
import '../src/cardu/cardu.less';
import '../src/cascader/index.less';
import '../src/cascaderbak/index.less';
import '../src/cell-group/index.less';
import '../src/cell/index.less';
import '../src/cellson/index.less';
import '../src/checkbox-group/index.less';
import '../src/checkbox/index.less';
import '../src/circle/index.less';
import '../src/col/index.less';
import '../src/collapse-item/index.less';
import '../src/contact-card/index.less';
import '../src/contact-edit/index.less';
import '../src/contact-list/index.less';
import '../src/count-down/index.less';
import '../src/coupon-cell/index.less';
import '../src/coupon-list/index.less';
import '../src/coupon/index.less';
import '../src/datetime-picker/index.less';
import '../src/dialog/index.less';
import '../src/divider/index.less';
import '../src/dropdown-item/index.less';
import '../src/dropdown-menu/index.less';
import '../src/empty/index.less';
import '../src/field/index.less';
import '../src/fieldinput/index.less';
import '../src/fieldsonforsearch/index.less';
import '../src/fieldtextarea/index.less';
import '../src/for-components/index.less';
import '../src/form/index.less';
import '../src/gallery/index.less';
import '../src/goods-action-button/index.less';
import '../src/goods-action-icon/index.less';
import '../src/goods-action/index.less';
import '../src/grid-item/index.less';
import '../src/grid/index.less';
import '../src/icon/index.less';
import '../src/icon/local.less';
import '../src/iconv/index.less';
import '../src/iconv/local.less';
import '../src/image-preview/index.less';
import '../src/image/index.less';
import '../src/index-anchor/index.less';
import '../src/index-bar/index.less';
import '../src/info/index.less';
import '../src/linear-layout/index.less';
import '../src/list/index.less';
import '../src/loading/index.less';
import '../src/nav-bar/index.less';
import '../src/notice-bar/index.less';
import '../src/notify/index.less';
import '../src/number-keyboard/index.less';
import '../src/pagination/index.less';
import '../src/panel/index.less';
import '../src/password-input/index.less';
import '../src/picker/index.less';
import '../src/pickerson/index.less';
import '../src/popover-combination/index.less';
import '../src/popover/index.less';
import '../src/progress/index.less';
import '../src/pull-refresh/index.less';
import '../src/radio-group/index.less';
import '../src/radio/index.less';
import '../src/rate/index.less';
import '../src/row/index.less';
import '../src/search/index.less';
import '../src/share-sheet/index.less';
import '../src/sidebar-item/index.less';
import '../src/sidebar/index.less';
import '../src/skeleton/index.less';
import '../src/sku/index.less';
import '../src/slider/index.less';
import '../src/step/index.less';
import '../src/stepper-new/index.less';
import '../src/stepper/index.less';
import '../src/steps/index.less';
import '../src/sticky/index.less';
import '../src/submit-bar/index.less';
import '../src/swipe-cell/index.less';
import '../src/swipe-item/index.less';
import '../src/swipe/index.less';
import '../src/switch-cell/index.less';
import '../src/switch/index.less';
import '../src/tab/index.less';
import '../src/tabbar-item/index.less';
import '../src/tabbar/index.less';
import '../src/tabs/index.less';
import '../src/tag/index.less';
import '../src/toast/index.less';
import '../src/tree-select/index.less';
import '../src/uploader/index.less';
import '../src/my-process/index.less';
import '../src/process-button/index.less';
import '../src/process-info/index.less';
import '../src/process-record/index.less';

// 保证在H5样式之后
/* 引入cloud-ui theme */
import 'cloud-ui.vusion/src/styles/theme.css';
/* 引入cloud-ui typography */
import 'cloud-ui.vusion/src/styles/typography.css';
/* 引入cloud-ui animation */
import 'cloud-ui.vusion/src/styles/animation.css';
