// export { default as Button } from './components/Button/index';
export * from './components/Button/index';
// export { default as Select } from './components/Select/index';
export * from './components/Select/index';
export * from './components/InputNumber/index';
export * from './components/Text/index';
// export { default as Text } from './components/Text/index';
// export { default as Table } from './components/Table/index';
export * from './components/Table/index';
// export { default as Flex } from './components/Flex/index';
export * from './components/Flex/index';
export { TableColumn } from './components/Table/index';
export * from './components/Transfer/index';
export * from './components/Tabs/index';
export * from './components/Switch/index';
export * from './components/Row/index';
export * from './components/Modal/index';
export * from './components/Message/index';
export * from './components/Drawer/index';
export * from './components/Tree/index';
export * from './components/Popover/index';
export * from './components/Image/index';
export * from './components/TreeSelect/index';
export * from './components/Button/index';
export * from './components/Cascader/index';
export * from './components/Card/index';
export * from './components/Input/index';
export * from './components/TextArea/index';
export * from './components/Descriptions/index';
export * from './components/DatePicker/index';
export * from './components/DateRangePicker/index';
export * from './components/TimePicker/index';
export * from './components/TimeRangePicker/index';
export * from './components/Breadcrumb/index';
export * from './components/Dropdown/index';
export * from './components/Checkbox/index';
export * from './components/Radio/index';
export * from './components/List/index';
export * from './components/Steps/index';
export * from './components/Router/index';
export * from './components/Menu/index';
export * from './components/Form/index';
export * from './components/Upload/index';
export * from './components/Icon/index';

// export * from './components/Typography/index';
// export * from 'antd';
