export const $formProvide = '__LCAP_UI_EL_FORM_PROVIDE__';
export const $formItemProps = [
  'error',
  'for',
  'inlineMessage',
  'label',
  'labelPosition',
  'labelWidth',
  'rules',
  'prop',
  'showMessage',
  'size',
  'isRequired',
  'onValidateSuccess',
  'validateStatus',
  'data-nodepath',
  'data-enable-events',
  'trigger',
  'ignoreRules',
  'prop',
];
