"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var fs = require("fs-extra");
var path = require("path");
var ts2usage_1 = require("./common/ts2usage");
var argv = require('minimist')(process.argv.slice(2));
var cwd = process.cwd();
var root = path.join(cwd, argv.root || '') || path.join(__dirname, "../../cloud-ui");
console.log('root: ', root);
var data = (0, ts2usage_1.default)(root);
var output = path.join(cwd, argv.dest) || path.join(__dirname, "../pc.nasl.ui.json");
fs.writeFileSync(output, JSON.stringify(data, null, 2));
