module.exports = {
  "--cw-color-fill-content": "var(--cw-color-fill-secondary)",
  "--cw-color-fill-content-hover": "var(--cw-color-fill)",
  "--cw-color-fill-alter": "var(--cw-color-fill-quaternary)",
  "--cw-color-bg-container-disabled": "var(--cw-color-fill-tertiary)",
  "--cw-color-border-bg": "var(--cw-color-bg-container)",
  "--cw-color-text-placeholder": "var(--cw-color-text-quaternary)",
  "--cw-color-text-disabled": "var(--cw-color-text-quaternary)",
  "--cw-color-text-heading": "var(--cw-color-text)",
  "--cw-color-text-label": "var(--cw-color-text-secondary)",
  "--cw-color-text-description": "var(--cw-color-text-tertiary)",
  "--cw-color-text-light-solid": "var(--cw-color-white)",
  "--cw-color-highlight": "var(--cw-color-error)",
  "--cw-color-bg-text-hover": "var(--cw-color-fill-secondary)",
  "--cw-color-bg-text-active": "var(--cw-color-fill)",
  "--cw-color-icon": "var(--cw-color-text-tertiary)",
  "--cw-color-icon-hover": "var(--cw-color-text)",
  "--cw-font-size-icon": "var(--cw-font-size-sm)",
  "--cw-control-item-bg-hover": "var(--cw-color-fill-tertiary)",
  "--cw-control-item-bg-active": "var(--cw-color-primary-bg)",
  "--cw-control-item-bg-active-hover": "var(--cw-color-primary-bg-hover)",
  "--cw-control-item-bg-active-disabled": "var(--cw-color-fill)",
  "--cw-control-tmp-outline": "var(--cw-color-fill-quaternary)",
  "--cw-padding-xxs": "var(--cw-size-xxs)",
  "--cw-padding-xs": "var(--cw-size-xs)",
  "--cw-padding-sm": "var(--cw-size-sm)",
  "--cw-padding": "var(--cw-size)",
  "--cw-padding-md": "var(--cw-size-md)",
  "--cw-padding-lg": "var(--cw-size-lg)",
  "--cw-padding-xl": "var(--cw-size-xl)",
  "--cw-padding-content-horizontal-lg": "var(--cw-size-lg)",
  "--cw-padding-content-vertical-lg": "var(--cw-size-ms)",
  "--cw-padding-content-horizontal": "var(--cw-size-ms)",
  "--cw-padding-content-vertical": "var(--cw-size-sm)",
  "--cw-padding-content-horizontal-sm": "var(--cw-size)",
  "--cw-padding-content-vertical-sm": "var(--cw-size-xs)",
  "--cw-margin-xxs": "var(--cw-size-xxs)",
  "--cw-margin-xs": "var(--cw-size-xs)",
  "--cw-margin-sm": "var(--cw-size-sm)",
  "--cw-margin": "var(--cw-size)",
  "--cw-margin-md": "var(--cw-size-md)",
  "--cw-margin-lg": "var(--cw-size-lg)",
  "--cw-margin-xl": "var(--cw-size-xl)",
  "--cw-margin-xxl": "var(--cw-size-xxl)",
  "--cw-line-width-focus": 'calc(var(--cw-line-width) * 4)',
  "--cw-control-outline-width": 'calc(var(--cw-line-width) * 2)',
  '--cw-control-interactive-size': 'calc(var(--cw-control-height) / 2)',
  '--cw-affix-z-index-popup': 'calc(var(--cw-z-index-base) + 10)',
  "--cw-alert-with-description-icon-size": "var(--cw-font-size-heading-3)",
  "--cw-alert-default-padding": "var(--cw-padding-content-vertical-sm) 12px",
  "--cw-alert-with-description-padding": "var(--cw-padding-md) var(--cw-padding-content-horizontal-lg)",
  "--cw-anchor-link-padding-block": "var(--cw-padding-xxs)",
  "--cw-anchor-link-padding-inline-start": "var(--cw-padding)",
  "--cw-avatar-container-size": "var(--cw-control-height)",
  "--cw-avatar-container-size-lg": "var(--cw-control-height-lg)",
  "--cw-avatar-container-size-sm": "var(--cw-control-height-sm)",
  "--cw-avatar-text-font-size": "calc(calc(var(--cw-font-size-lg) + var(--cw-font-size-xl)) / 2)",
  "--cw-avatar-text-font-size-lg": "var(--cw-font-size-heading-3)",
  "--cw-avatar-text-font-size-sm": "var(--cw-font-size)",
  "--cw-avatar-group-space": "var(--cw-margin-xxs)",
  "--cw-avatar-group-overlapping": "-var(--cw-margin-xs)",
  "--cw-avatar-group-border-color": "var(--cw-color-border-bg)",
  "--cw-back-top-z-index-popup": "calc(var(--cw-z-index-base) + 10)",
  "--cw-badge-indicator-height": "calc(calc(var(--cw-font-size) * var(--cw-line-height)) - calc(var(--cw-line-width) * 2))",
  "--cw-badge-indicator-height-sm": "var(--cw-font-size)",
  "--cw-badge-dot-size": "calc(var(--cw-font-size-sm) / 2)",
  "--cw-badge-text-font-size": "var(--cw-font-size-sm)",
  "--cw-badge-text-font-size-sm": "var(--cw-font-size-sm)",
  "--cw-badge-status-size": "calc(var(--cw-font-size-sm) / 2)",
  "--cw-breadcrumb-item-color": "var(--cw-color-text-description)",
  "--cw-breadcrumb-last-item-color": "var(--cw-color-text)",
  "--cw-breadcrumb-icon-font-size": "var(--cw-font-size)",
  "--cw-breadcrumb-link-color": "var(--cw-color-text-description)",
  "--cw-breadcrumb-link-hover-color": "var(--cw-color-text)",
  "--cw-breadcrumb-separator-color": "var(--cw-color-text-description)",
  "--cw-breadcrumb-separator-margin": "var(--cw-margin-xs)",
  "--cw-button-default-shadow": "0 var(--cw-control-outline-width) 0 var(--cw-control-tmp-outline)",
  "--cw-button-primary-shadow": "0 var(--cw-control-outline-width) 0 var(--cw-control-outline)",
  "--cw-button-danger-shadow": "0 var(--cw-control-outline-width) 0 var(--cw-color-error-outline)",
  "--cw-button-primary-color": "var(--cw-color-text-light-solid)",
  "--cw-button-danger-color": "var(--cw-color-text-light-solid)",
  "--cw-button-border-color-disabled": "var(--cw-color-border)",
  "--cw-button-default-ghost-color": "var(--cw-color-bg-container)",
  "--cw-button-default-ghost-border-color": "var(--cw-color-bg-container)",
  "--cw-button-padding-inline": "calc(var(--cw-padding-content-horizontal) - var(--cw-line-width))",
  "--cw-button-padding-inline-lg": "calc(var(--cw-padding-content-horizontal) - var(--cw-line-width))",
  "--cw-button-padding-inline-sm": "calc(8px - var(--cw-line-width))",
  "--cw-button-only-icon-size": "var(--cw-font-size-lg)",
  "--cw-button-only-icon-size-sm": "calc(var(--cw-font-size-lg) - 2px)",
  "--cw-button-only-icon-size-lg": "calc(var(--cw-font-size-lg) + 2px)",
  "--cw-button-group-border-color": "var(--cw-color-primary-hover)",
  "--cw-button-text-hover-bg": "var(--cw-color-bg-text-hover)",
  "--cw-button-default-color": "var(--cw-color-text)",
  "--cw-button-default-bg": "var(--cw-color-bg-container)",
  "--cw-button-default-border-color": "var(--cw-color-border)",
  "--cw-button-default-border-color-disabled": "var(--cw-color-border)",
  "--cw-button-default-hover-bg": "var(--cw-color-bg-container)",
  "--cw-button-default-hover-color": "var(--cw-color-primary-hover)",
  "--cw-button-default-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-button-default-active-bg": "var(--cw-color-bg-container)",
  "--cw-button-default-active-color": "var(--cw-color-primary-active)",
  "--cw-button-default-active-border-color": "var(--cw-color-primary-active)",
  "--cw-button-content-font-size": "var(--cw-font-size)",
  "--cw-button-content-font-size-sm": "var(--cw-font-size)",
  "--cw-button-content-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-button-content-line-height": "calc(calc(var(--cw-font-size) + 8px) / var(--cw-font-size))",
  "--cw-button-content-line-height-sm": "calc(calc(var(--cw-font-size) + 8px) / var(--cw-font-size))",
  "--cw-button-content-line-height-lg": "calc(calc(var(--cw-font-size-lg) + 8px) / var(--cw-font-size-lg))",
  "--cw-calendar-full-bg": "var(--cw-color-bg-container)",
  "--cw-calendar-full-panel-bg": "var(--cw-color-bg-container)",
  "--cw-calendar-item-active-bg": "var(--cw-control-item-bg-active)",
  "--cw-card-header-font-size": "var(--cw-font-size-lg)",
  "--cw-card-header-font-size-sm": "var(--cw-font-size)",
  "--cw-card-header-height": "calc(calc(var(--cw-font-size-lg) * var(--cw-line-height-lg)) + calc(var(--cw-padding) * 2))",
  "--cw-card-header-height-sm": "calc(calc(var(--cw-font-size-lg) * var(--cw-line-height)) + calc(var(--cw-padding-xs) * 2))",
  "--cw-card-actions-bg": "var(--cw-color-bg-container)",
  "--cw-card-actions-li-margin": "var(--cw-padding-sm) 0",
  "--cw-card-tabs-margin-bottom": "calc(calc(var(--cw-padding) + var(--cw-line-width)) * -1)",
  "--cw-card-extra-color": "var(--cw-color-text)",
  "--cw-cascader-option-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-cascader-option-selected-font-weight": "var(--cw-font-weight-strong)",
  "--cw-cascader-option-padding": "calc(calc(var(--cw-control-height) - calc(var(--cw-font-size) * var(--cw-line-height))) / 2) var(--cw-padding-sm)",
  "--cw-cascader-menu-padding": "var(--cw-padding-xxs)",
  "--cw-collapse-header-padding": "var(--cw-padding-sm) var(--cw-padding)",
  "--cw-collapse-header-bg": "var(--cw-color-fill-alter)",
  "--cw-collapse-content-padding": "var(--cw-padding) 16px",
  "--cw-collapse-content-bg": "var(--cw-color-bg-container)",
  "--cw-date-picker-padding-inline": "calc(var(--cw-padding-sm) - var(--cw-line-width))",
  "--cw-date-picker-padding-inline-sm": "calc(var(--cw-control-padding-horizontal-sm) - var(--cw-line-width))",
  "--cw-date-picker-padding-inline-lg": "calc(var(--cw-control-padding-horizontal) - var(--cw-line-width))",
  "--cw-date-picker-addon-bg": "var(--cw-color-fill-alter)",
  "--cw-date-picker-active-border-color": "var(--cw-color-primary)",
  "--cw-date-picker-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-date-picker-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-control-outline)",
  "--cw-date-picker-error-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-error-outline)",
  "--cw-date-picker-warning-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-warning-outline)",
  "--cw-date-picker-hover-bg": "var(--cw-color-bg-container)",
  "--cw-date-picker-active-bg": "var(--cw-color-bg-container)",
  "--cw-date-picker-input-font-size": "var(--cw-font-size)",
  "--cw-date-picker-input-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-date-picker-input-font-size-sm": "var(--cw-font-size)",
  "--cw-date-picker-cell-hover-bg": "var(--cw-control-item-bg-hover)",
  "--cw-date-picker-cell-active-with-range-bg": "var(--cw-control-item-bg-active)",
  "--cw-date-picker-cell-bg-disabled": "var(--cw-color-bg-container-disabled)",
  "--cw-date-picker-time-column-width": "calc(var(--cw-control-height-lg) * 1.4)",
  "--cw-date-picker-cell-width": "calc(var(--cw-control-height-sm) * 1.5)",
  "--cw-date-picker-cell-height": "var(--cw-control-height-sm)",
  "--cw-date-picker-text-height": "var(--cw-control-height-lg)",
  "--cw-date-picker-without-time-cell-height": "calc(var(--cw-control-height-lg) * 1.65)",
  "--cw-date-picker-multiple-item-bg": "var(--cw-color-fill-secondary)",
  "--cw-date-picker-multiple-item-height": "var(--cw-control-height-sm)",
  "--cw-date-picker-multiple-item-height-lg": "var(--cw-control-height)",
  "--cw-date-picker-multiple-selector-bg-disabled": "var(--cw-color-bg-container-disabled)",
  "--cw-date-picker-multiple-item-color-disabled": "var(--cw-color-text-disabled)",
  "--cw-descriptions-label-bg": "var(--cw-color-fill-alter)",
  "--cw-descriptions-title-color": "var(--cw-color-text)",
  "--cw-descriptions-title-margin-bottom": "calc(var(--cw-font-size-sm) * var(--cw-line-height-sm))",
  "--cw-descriptions-item-padding-bottom": "var(--cw-padding)",
  "--cw-descriptions-colon-margin-right": "var(--cw-margin-xs)",
  "--cw-descriptions-colon-margin-left": "calc(var(--cw-margin-xxs) / 2)",
  "--cw-descriptions-content-color": "var(--cw-color-text)",
  "--cw-descriptions-extra-color": "var(--cw-color-text)",
  "--cw-divider-vertical-margin-inline": "var(--cw-margin-xs)",
  "--cw-drawer-z-index-popup": "var(--cw-z-index-popup-base)",
  "--cw-drawer-footer-padding-block": "var(--cw-padding-xs)",
  "--cw-drawer-footer-padding-inline": "var(--cw-padding)",
  "--cw-form-label-required-mark-color": "var(--cw-color-error)",
  "--cw-form-label-color": "var(--cw-color-text-heading)",
  "--cw-form-label-font-size": "var(--cw-font-size)",
  "--cw-form-label-height": "var(--cw-control-height)",
  "--cw-form-label-colon-margin-inline-start": "calc(var(--cw-margin-xxs) / 2)",
  "--cw-form-label-colon-margin-inline-end": "var(--cw-margin-xs)",
  "--cw-form-item-margin-bottom": "var(--cw-margin-lg)",
  "--cw-form-vertical-label-padding": "0 0 var(--cw-padding-xs)",
  "--cw-image-preview-operation-size": "calc(var(--cw-font-size-icon) * 1.5)",
  "--cw-input-padding-inline": "calc(var(--cw-padding-sm) - var(--cw-line-width))",
  "--cw-input-padding-inline-sm": "calc(var(--cw-control-padding-horizontal-sm) - var(--cw-line-width))",
  "--cw-input-padding-inline-lg": "calc(var(--cw-control-padding-horizontal) - var(--cw-line-width))",
  "--cw-input-addon-bg": "var(--cw-color-fill-alter)",
  "--cw-input-active-border-color": "var(--cw-color-primary)",
  "--cw-input-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-input-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-control-outline)",
  "--cw-input-error-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-error-outline)",
  "--cw-input-warning-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-warning-outline)",
  "--cw-input-hover-bg": "var(--cw-color-bg-container)",
  "--cw-input-active-bg": "var(--cw-color-bg-container)",
  "--cw-input-input-font-size": "var(--cw-font-size)",
  "--cw-input-input-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-input-input-font-size-sm": "var(--cw-font-size)",
  "--cw-input-number-padding-inline": "calc(var(--cw-padding-sm) - var(--cw-line-width))",
  "--cw-input-number-padding-inline-sm": "calc(var(--cw-control-padding-horizontal-sm) - var(--cw-line-width))",
  "--cw-input-number-padding-inline-lg": "calc(var(--cw-control-padding-horizontal) - var(--cw-line-width))",
  "--cw-input-number-addon-bg": "var(--cw-color-fill-alter)",
  "--cw-input-number-active-border-color": "var(--cw-color-primary)",
  "--cw-input-number-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-input-number-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-control-outline)",
  "--cw-input-number-error-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-error-outline)",
  "--cw-input-number-warning-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-warning-outline)",
  "--cw-input-number-hover-bg": "var(--cw-color-bg-container)",
  "--cw-input-number-active-bg": "var(--cw-color-bg-container)",
  "--cw-input-number-input-font-size": "var(--cw-font-size)",
  "--cw-input-number-input-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-input-number-input-font-size-sm": "var(--cw-font-size)",
  "--cw-input-number-handle-width": "calc(var(--cw-control-height-sm) - calc(var(--cw-line-width) * 2))",
  "--cw-input-number-handle-font-size": "calc(var(--cw-font-size) / 2)",
  "--cw-input-number-handle-active-bg": "var(--cw-color-fill-alter)",
  "--cw-input-number-handle-bg": "var(--cw-color-bg-container)",
  "--cw-input-number-handle-hover-color": "var(--cw-color-primary)",
  "--cw-input-number-handle-border-color": "var(--cw-color-border)",
  "--cw-layout-color-bg-body": "var(--cw-color-bg-layout)",
  "--cw-layout-body-bg": "var(--cw-color-bg-layout)",
  "--cw-layout-header-height": "calc(var(--cw-control-height) * 2)",
  "--cw-layout-header-padding": "0 var(--cw-padding-inline)",
  "--cw-layout-header-color": "var(--cw-color-text)",
  "--cw-layout-footer-padding": "var(--cw-control-height-sm) var(--cw-padding-inline)",
  "--cw-layout-footer-bg": "var(--cw-color-bg-layout)",
  "--cw-layout-trigger-height": "calc(var(--cw-control-height-lg) + calc(var(--cw-margin-xxs) * 2))",
  "--cw-layout-trigger-color": "var(--cw-color-text-light-solid)",
  "--cw-layout-zero-trigger-width": "var(--cw-control-height-lg)",
  "--cw-layout-zero-trigger-height": "var(--cw-control-height-lg)",
  "--cw-layout-light-sider-bg": "var(--cw-color-bg-container)",
  "--cw-layout-light-trigger-bg": "var(--cw-color-bg-container)",
  "--cw-layout-light-trigger-color": "var(--cw-color-text)",
  "--cw-list-item-padding": "var(--cw-padding-content-vertical) 0",
  "--cw-list-item-padding-sm": "var(--cw-padding-content-vertical-sm) var(--cw-padding-content-horizontal)",
  "--cw-list-item-padding-lg": "var(--cw-padding-content-vertical-lg) var(--cw-padding-content-horizontal-lg)",
  "--cw-list-empty-text-padding": "var(--cw-padding)",
  "--cw-list-meta-margin-bottom": "var(--cw-padding)",
  "--cw-list-avatar-margin-right": "var(--cw-padding)",
  "--cw-list-title-margin-bottom": "var(--cw-padding-sm)",
  "--cw-list-description-font-size": "var(--cw-font-size)",
  "--cw-mentions-padding-inline": "calc(var(--cw-padding-sm) - var(--cw-line-width))",
  "--cw-mentions-padding-inline-sm": "calc(var(--cw-control-padding-horizontal-sm) - var(--cw-line-width))",
  "--cw-mentions-padding-inline-lg": "calc(var(--cw-control-padding-horizontal) - var(--cw-line-width))",
  "--cw-mentions-addon-bg": "var(--cw-color-fill-alter)",
  "--cw-mentions-active-border-color": "var(--cw-color-primary)",
  "--cw-mentions-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-mentions-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-control-outline)",
  "--cw-mentions-error-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-error-outline)",
  "--cw-mentions-warning-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-warning-outline)",
  "--cw-mentions-hover-bg": "var(--cw-color-bg-container)",
  "--cw-mentions-active-bg": "var(--cw-color-bg-container)",
  "--cw-mentions-input-font-size": "var(--cw-font-size)",
  "--cw-mentions-input-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-mentions-input-font-size-sm": "var(--cw-font-size)",
  "--cw-mentions-z-index-popup": "calc(var(--cw-z-index-popup-base) + 50)",
  "--cw-mentions-item-padding-vertical": "calc(calc(var(--cw-control-height) - var(--cw-font-height)) / 2)",
  "--cw-menu-z-index-popup": "calc(var(--cw-z-index-popup-base) + 50)",
  "--cw-menu-radius-item": "var(--cw-border-radius-lg)",
  "--cw-menu-item-border-radius": "var(--cw-border-radius-lg)",
  "--cw-menu-radius-sub-menu-item": "var(--cw-border-radius-sm)",
  "--cw-menu-sub-menu-item-border-radius": "var(--cw-border-radius-sm)",
  "--cw-menu-color-item-text": "var(--cw-color-text)",
  "--cw-menu-item-color": "var(--cw-color-text)",
  "--cw-menu-color-item-text-hover": "var(--cw-color-text)",
  "--cw-menu-item-hover-color": "var(--cw-color-text)",
  "--cw-menu-color-item-text-hover-horizontal": "var(--cw-color-primary)",
  "--cw-menu-horizontal-item-hover-color": "var(--cw-color-primary)",
  "--cw-menu-color-group-title": "var(--cw-color-text-description)",
  "--cw-menu-group-title-color": "var(--cw-color-text-description)",
  "--cw-menu-color-item-text-selected": "var(--cw-color-primary)",
  "--cw-menu-item-selected-color": "var(--cw-color-primary)",
  "--cw-menu-color-item-text-selected-horizontal": "var(--cw-color-primary)",
  "--cw-menu-horizontal-item-selected-color": "var(--cw-color-primary)",
  "--cw-menu-color-item-bg": "var(--cw-color-bg-container)",
  "--cw-menu-item-bg": "var(--cw-color-bg-container)",
  "--cw-menu-color-item-bg-hover": "var(--cw-color-bg-text-hover)",
  "--cw-menu-item-hover-bg": "var(--cw-color-bg-text-hover)",
  "--cw-menu-color-item-bg-active": "var(--cw-color-fill-content)",
  "--cw-menu-item-active-bg": "var(--cw-control-item-bg-active)",
  "--cw-menu-color-sub-item-bg": "var(--cw-color-fill-alter)",
  "--cw-menu-sub-menu-item-bg": "var(--cw-color-fill-alter)",
  "--cw-menu-color-item-bg-selected": "var(--cw-control-item-bg-active)",
  "--cw-menu-item-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-menu-color-active-bar-height": "var(--cw-line-width-bold)",
  "--cw-menu-active-bar-height": "var(--cw-line-width-bold)",
  "--cw-menu-color-active-bar-border-size": "var(--cw-line-width)",
  "--cw-menu-active-bar-border-width": "var(--cw-line-width)",
  "--cw-menu-color-item-text-disabled": "var(--cw-color-text-disabled)",
  "--cw-menu-item-disabled-color": "var(--cw-color-text-disabled)",
  "--cw-menu-color-danger-item-text": "var(--cw-color-error)",
  "--cw-menu-danger-item-color": "var(--cw-color-error)",
  "--cw-menu-color-danger-item-text-hover": "var(--cw-color-error)",
  "--cw-menu-danger-item-hover-color": "var(--cw-color-error)",
  "--cw-menu-color-danger-item-text-selected": "var(--cw-color-error)",
  "--cw-menu-danger-item-selected-color": "var(--cw-color-error)",
  "--cw-menu-color-danger-item-bg-active": "var(--cw-color-error-bg)",
  "--cw-menu-danger-item-active-bg": "var(--cw-color-error-bg)",
  "--cw-menu-color-danger-item-bg-selected": "var(--cw-color-error-bg)",
  "--cw-menu-danger-item-selected-bg": "var(--cw-color-error-bg)",
  "--cw-menu-item-margin-inline": "var(--cw-margin-xxs)",
  "--cw-menu-item-height": "var(--cw-control-height-lg)",
  "--cw-menu-group-title-line-height": "var(--cw-line-height)",
  "--cw-menu-collapsed-width": "calc(var(--cw-control-height-lg) * 2)",
  "--cw-menu-popup-bg": "var(--cw-color-bg-elevated)",
  "--cw-menu-item-margin-block": "var(--cw-margin-xxs)",
  "--cw-menu-item-padding-inline": "var(--cw-padding)",
  "--cw-menu-horizontal-line-height": "calc(var(--cw-control-height-lg) * 1.15)",
  "--cw-menu-icon-size": "var(--cw-font-size)",
  "--cw-menu-icon-margin-inline-end": "calc(var(--cw-control-height-sm) - var(--cw-font-size))",
  "--cw-menu-collapsed-icon-size": "var(--cw-font-size-lg)",
  "--cw-menu-group-title-font-size": "var(--cw-font-size)",
  "--cw-menu-dark-item-color": "var(--cw-color-text-dark)",
  "--cw-menu-dark-danger-item-color": "var(--cw-color-error)",
  "--cw-menu-dark-item-selected-color": "var(--cw-color-text-light-solid)",
  "--cw-menu-dark-item-selected-bg": "var(--cw-color-primary)",
  "--cw-menu-dark-danger-item-selected-bg": "var(--cw-color-error)",
  "--cw-menu-dark-group-title-color": "var(--cw-color-text-dark)",
  "--cw-menu-dark-item-hover-color": "var(--cw-color-text-light-solid)",
  "--cw-menu-dark-danger-item-hover-color": "var(--cw-color-error-hover)",
  "--cw-menu-dark-danger-item-selected-color": "var(--cw-color-text-light-solid)",
  "--cw-menu-dark-danger-item-active-bg": "var(--cw-color-error)",
  "--cw-message-content-bg": "var(--cw-color-bg-elevated)",
  "--cw-message-content-padding": "calc(calc(var(--cw-control-height-lg) - calc(var(--cw-font-size) * var(--cw-line-height))) / 2) var(--cw-padding-sm)",
  "--cw-modal-header-bg": "var(--cw-color-bg-elevated)",
  "--cw-modal-title-line-height": "var(--cw-line-height-heading-5)",
  "--cw-modal-title-font-size": "var(--cw-font-size-heading-5)",
  "--cw-modal-content-bg": "var(--cw-color-bg-elevated)",
  "--cw-modal-title-color": "var(--cw-color-text-heading)",
  "--cw-modal-close-btn-hover-bg": "var(--cw-color-fill-content)",
  "--cw-modal-close-btn-active-bg": "var(--cw-color-fill-content-hover)",
  "--cw-modal-content-padding": "var(--cw-padding-md) var(--cw-padding-content-horizontal-lg)",
  "--cw-notification-close-btn-hover-bg": "var(--cw-color-fill-content)",
  "--cw-pagination-item-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-item-size": "var(--cw-control-height)",
  "--cw-pagination-item-size-sm": "var(--cw-control-height-sm)",
  "--cw-pagination-item-active-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-item-link-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-item-active-color-disabled": "var(--cw-color-text-disabled)",
  "--cw-pagination-item-active-bg-disabled": "var(--cw-control-item-bg-active-disabled)",
  "--cw-pagination-item-input-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-padding-inline": "calc(var(--cw-padding-sm) - var(--cw-line-width))",
  "--cw-pagination-padding-inline-sm": "calc(var(--cw-control-padding-horizontal-sm) - var(--cw-line-width))",
  "--cw-pagination-padding-inline-lg": "calc(var(--cw-control-padding-horizontal) - var(--cw-line-width))",
  "--cw-pagination-addon-bg": "var(--cw-color-fill-alter)",
  "--cw-pagination-active-border-color": "var(--cw-color-primary)",
  "--cw-pagination-hover-border-color": "var(--cw-color-primary-hover)",
  "--cw-pagination-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-control-outline)",
  "--cw-pagination-error-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-error-outline)",
  "--cw-pagination-warning-active-shadow": "0 0 0 var(--cw-control-outline-width) var(--cw-color-warning-outline)",
  "--cw-pagination-hover-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-active-bg": "var(--cw-color-bg-container)",
  "--cw-pagination-input-font-size": "var(--cw-font-size)",
  "--cw-pagination-input-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-pagination-input-font-size-sm": "var(--cw-font-size)",
  "--cw-popconfirm-z-index-popup": "calc(var(--cw-z-index-popup-base) + 60)",
  "--cw-popover-z-index-popup": "calc(var(--cw-z-index-popup-base) + 30)",
  "--cw-progress-circle-text-color": "var(--cw-color-text)",
  "--cw-progress-default-color": "var(--cw-color-info)",
  "--cw-progress-remaining-color": "var(--cw-color-fill-secondary)",
  "--cw-radio-radio-size": "var(--cw-font-size-lg)",
  "--cw-radio-dot-color-disabled": "var(--cw-color-text-disabled)",
  "--cw-radio-button-solid-checked-color": "var(--cw-color-text-light-solid)",
  "--cw-radio-button-solid-checked-bg": "var(--cw-color-primary)",
  "--cw-radio-button-solid-checked-hover-bg": "var(--cw-color-primary-hover)",
  "--cw-radio-button-solid-checked-active-bg": "var(--cw-color-primary-active)",
  "--cw-radio-button-bg": "var(--cw-color-bg-container)",
  "--cw-radio-button-checked-bg": "var(--cw-color-bg-container)",
  "--cw-radio-button-color": "var(--cw-color-text)",
  "--cw-radio-button-checked-bg-disabled": "var(--cw-control-item-bg-active-disabled)",
  "--cw-radio-button-checked-color-disabled": "var(--cw-color-text-disabled)",
  "--cw-radio-button-padding-inline": "calc(var(--cw-padding) - var(--cw-line-width))",
  "--cw-radio-wrapper-margin-inline-end": "var(--cw-margin-xs)",
  "--cw-rate-star-size": "calc(var(--cw-control-height-lg) * 0.5)",
  "--cw-rate-star-bg": "var(--cw-color-fill-content)",
  "--cw-result-title-font-size": "var(--cw-font-size-heading-3)",
  "--cw-result-subtitle-font-size": "var(--cw-font-size)",
  "--cw-result-icon-font-size": "calc(var(--cw-font-size-heading-3) * 3)",
  "--cw-result-extra-margin": "var(--cw-padding-lg) 0 0 0",
  "--cw-segmented-track-padding": "var(--cw-line-width-bold)",
  "--cw-segmented-track-bg": "var(--cw-color-bg-layout)",
  "--cw-segmented-item-color": "var(--cw-color-text-label)",
  "--cw-segmented-item-hover-color": "var(--cw-color-text)",
  "--cw-segmented-item-hover-bg": "var(--cw-color-fill-secondary)",
  "--cw-segmented-item-selected-bg": "var(--cw-color-bg-elevated)",
  "--cw-segmented-item-active-bg": "var(--cw-color-fill)",
  "--cw-segmented-item-selected-color": "var(--cw-color-text)",
  "--cw-select-z-index-popup": "calc(var(--cw-z-index-popup-base) + 50)",
  "--cw-select-option-selected-color": "var(--cw-color-text)",
  "--cw-select-option-selected-font-weight": "var(--cw-font-weight-strong)",
  "--cw-select-option-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-select-option-active-bg": "var(--cw-control-item-bg-hover)",
  "--cw-select-option-padding": "calc(calc(var(--cw-control-height) - calc(var(--cw-font-size) * var(--cw-line-height))) / 2) var(--cw-control-padding-horizontal)",
  "--cw-select-option-font-size": "var(--cw-font-size)",
  "--cw-select-option-line-height": "var(--cw-line-height)",
  "--cw-select-option-height": "var(--cw-control-height)",
  "--cw-select-selector-bg": "var(--cw-color-bg-container)",
  "--cw-select-clear-bg": "var(--cw-color-bg-container)",
  "--cw-select-single-item-height-lg": "var(--cw-control-height-lg)",
  "--cw-select-multiple-item-bg": "var(--cw-color-fill-secondary)",
  "--cw-select-multiple-item-height": "var(--cw-control-height-sm)",
  "--cw-select-multiple-item-height-lg": "var(--cw-control-height)",
  "--cw-select-multiple-selector-bg-disabled": "var(--cw-color-bg-container-disabled)",
  "--cw-select-multiple-item-color-disabled": "var(--cw-color-text-disabled)",
  "--cw-select-show-arrow-padding-inline-end": "calc(var(--cw-font-size) * 1.25)",
  "--cw-skeleton-color": "var(--cw-color-fill-content)",
  "--cw-skeleton-color-gradient-end": "var(--cw-color-fill)",
  "--cw-skeleton-gradient-from-color": "var(--cw-color-fill-content)",
  "--cw-skeleton-gradient-to-color": "var(--cw-color-fill)",
  "--cw-skeleton-title-height": "calc(var(--cw-control-height) / 2)",
  "--cw-skeleton-block-radius": "var(--cw-border-radius-sm)",
  "--cw-skeleton-paragraph-margin-top": "calc(var(--cw-margin-lg) + var(--cw-margin-xxs))",
  "--cw-skeleton-paragraph-li-height": "calc(var(--cw-token-control-height) / 2)",
  "--cw-slider-control-size": "calc(var(--cw-control-height-lg) / 4)",
  "--cw-slider-handle-size": "calc(var(--cw-control-height-lg) / 4)",
  "--cw-slider-handle-size-hover": "calc(var(--cw-control-height-sm) / 2)",
  "--cw-slider-handle-line-width": "calc(var(--cw-line-width) + 1px)",
  "--cw-slider-handle-line-width-hover": "calc(var(--cw-line-width) + 3px)",
  "--cw-slider-rail-bg": "var(--cw-color-fill-tertiary)",
  "--cw-slider-rail-hover-bg": "var(--cw-color-fill-secondary)",
  "--cw-slider-track-bg": "var(--cw-color-primary-border)",
  "--cw-slider-track-hover-bg": "var(--cw-color-primary-border-hover)",
  "--cw-slider-handle-color": "var(--cw-color-primary-border)",
  "--cw-slider-handle-active-color": "var(--cw-color-primary)",
  "--cw-slider-dot-border-color": "var(--cw-color-border-secondary)",
  "--cw-slider-dot-active-border-color": "var(--cw-color-primary-border)",
  "--cw-slider-track-bg-disabled": "var(--cw-color-bg-container-disabled)",
  "--cw-spin-dot-size": "calc(var(--cw-control-height-lg) / 2)",
  "--cw-spin-dot-size-sm": "calc(var(--cw-control-height-lg) * 0.35)",
  "--cw-spin-dot-size-lg": "var(--cw-control-height)",
  "--cw-statistic-title-font-size": "var(--cw-font-size)",
  "--cw-statistic-content-font-size": "var(--cw-font-size-heading-3)",
  "--cw-steps-title-line-height": "var(--cw-control-height)",
  "--cw-steps-custom-icon-size": "var(--cw-control-height)",
  "--cw-steps-custom-icon-font-size": "var(--cw-control-height-sm)",
  "--cw-steps-icon-size": "var(--cw-control-height)",
  "--cw-steps-icon-font-size": "var(--cw-font-size)",
  "--cw-steps-icon-size-sm": "var(--cw-font-size-heading-3)",
  "--cw-steps-dot-size": "calc(var(--cw-control-height) / 4)",
  "--cw-steps-dot-current-size": "calc(var(--cw-control-height-lg) / 4)",
  "--cw-steps-nav-arrow-color": "var(--cw-color-text-disabled)",
  "--cw-steps-wait-icon-color": "var(--cw-color-text-label)",
  "--cw-steps-wait-icon-bg-color": "var(--cw-color-fill-content)",
  "--cw-steps-finish-icon-bg-color": "var(--cw-control-item-bg-active)",
  "--cw-steps-finish-icon-border-color": "var(--cw-control-item-bg-active)",
  "--cw-switch-track-height": "calc(var(--cw-font-size) * var(--cw-line-height))",
  "--cw-switch-track-height-sm": "calc(var(--cw-control-height) / 2)",
  "--cw-switch-track-min-width": "calc(calc(calc(var(--cw-font-size) * var(--cw-line-height) - 4px) * 2) + 8px)",
  "--cw-switch-track-min-width-sm": "calc(calc(var(--cw-control-height) / 2 - 4px) * 2 + 4px)",
  "--cw-switch-handle-size": "calc(var(--cw-font-size) * var(--cw-line-height) - 4px)",
  "--cw-switch-handle-size-sm": "calc(var(--cw-control-height) / 2 - 4px)",
  "--cw-switch-inner-min-margin": "calc(calc(var(--cw-font-size) * var(--cw-line-height) - 4px) / 2)",
  "--cw-switch-inner-max-margin": "calc(calc(var(--cw-font-size) * var(--cw-line-height) - 4px) + 6px)",
  "--cw-switch-inner-min-margin-sm": "calc(calc(var(--cw-control-height) / 2 - 4px) / 2)",
  "--cw-switch-inner-max-margin-sm": "calc(calc(var(--cw-control-height) / 2 - 4px) + 6px)",
  "--cw-table-header-color": "var(--cw-color-text-heading)",
  "--cw-table-row-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-table-row-selected-hover-bg": "var(--cw-control-item-bg-active-hover)",
  "--cw-table-row-expanded-bg": "var(--cw-color-fill-alter)",
  "--cw-table-cell-padding-block": "var(--cw-padding)",
  "--cw-table-cell-padding-inline": "var(--cw-padding)",
  "--cw-table-cell-padding-block-md": "var(--cw-padding-sm)",
  "--cw-table-cell-padding-inline-md": "var(--cw-padding-xs)",
  "--cw-table-cell-padding-block-sm": "var(--cw-padding-xs)",
  "--cw-table-cell-padding-inline-sm": "var(--cw-padding-xs)",
  "--cw-table-border-color": "var(--cw-color-border-secondary)",
  "--cw-table-header-border-radius": "var(--cw-border-radius-lg)",
  "--cw-table-footer-color": "var(--cw-color-text-heading)",
  "--cw-table-cell-font-size": "var(--cw-font-size)",
  "--cw-table-cell-font-size-md": "var(--cw-font-size)",
  "--cw-table-cell-font-size-sm": "var(--cw-font-size)",
  "--cw-table-header-split-color": "var(--cw-color-border-secondary)",
  "--cw-table-header-filter-hover-bg": "var(--cw-color-fill-content)",
  "--cw-table-filter-dropdown-menu-bg": "var(--cw-color-bg-container)",
  "--cw-table-filter-dropdown-bg": "var(--cw-color-bg-container)",
  "--cw-table-expand-icon-bg": "var(--cw-color-bg-container)",
  "--cw-table-selection-column-width": "var(--cw-control-height)",
  "--cw-table-sticky-scroll-bar-bg": "var(--cw-color-text-placeholder)",
  "--cw-tabs-z-index-popup": "calc(var(--cw-z-index-popup-base) + 50)",
  "--cw-tabs-card-bg": "var(--cw-color-fill-alter)",
  "--cw-tabs-card-height": "var(--cw-control-height-lg)",
  "--cw-tabs-card-padding": "calc(calc(var(--cw-control-height-lg) - calc(var(--cw-font-size) * var(--cw-line-height))) / 2 - var(--cw-line-width)) var(--cw-padding)",
  "--cw-tabs-card-padding-sm": "calc(var(--cw-padding-xxs) * 1.5) var(--cw-padding)",
  "--cw-tabs-card-padding-lg": "var(--cw-padding-xs) var(--cw-padding) calc(var(--cw-padding-xxs) * 1.5)",
  "--cw-tabs-title-font-size": "var(--cw-font-size)",
  "--cw-tabs-title-font-size-lg": "var(--cw-font-size-lg)",
  "--cw-tabs-title-font-size-sm": "var(--cw-font-size)",
  "--cw-tabs-ink-bar-color": "var(--cw-color-primary)",
  "--cw-tabs-horizontal-margin": "0 0 var(--cw-margin) 0",
  "--cw-tabs-horizontal-item-padding": "var(--cw-padding-sm) 0",
  "--cw-tabs-horizontal-item-padding-sm": "var(--cw-padding-xs) 0",
  "--cw-tabs-horizontal-item-padding-lg": "var(--cw-padding) 0",
  "--cw-tabs-vertical-item-padding": "var(--cw-padding-xs) var(--cw-padding-lg)",
  "--cw-tabs-vertical-item-margin": "var(--cw-margin) 0 0 0",
  "--cw-tabs-item-color": "var(--cw-color-text)",
  "--cw-tabs-item-selected-color": "var(--cw-color-primary)",
  "--cw-tabs-item-hover-color": "var(--cw-color-primary-hover)",
  "--cw-tabs-item-active-color": "var(--cw-color-primary-active)",
  "--cw-tabs-card-gutter": "calc(var(--cw-margin-xxs) / 2)",
  "--cw-tag-default-color": "var(--cw-color-text)",
  "--cw-timeline-tail-color": "var(--cw-color-split)",
  "--cw-timeline-tail-width": "var(--cw-line-width-bold)",
  "--cw-timeline-dot-border-width": "calc(var(--cw-line-width) * 3)",
  "--cw-timeline-dot-bg": "var(--cw-color-bg-container)",
  "--cw-timeline-item-padding-bottom": "calc(var(--cw-padding) * 1.25)",
  "--cw-tooltip-z-index-popup": "calc(var(--cw-z-index-popup-base) + 70)",
  "--cw-tour-z-index-popup": "calc(var(--cw-z-index-popup-base) + 70)",
  "--cw-transfer-header-height": "var(--cw-control-height-lg)",
  "--cw-transfer-item-height": "var(--cw-control-height)",
  "--cw-transfer-item-padding-block": "calc(calc(var(--cw-control-height) - var(--cw-font-height)) / 2)",
  "--cw-transfer-transfer-header-vertical-padding": "calc(calc(var(--cw-control-height-lg) - var(--cw-line-width) - var(--cw-font-height)) / 2)",
  "--cw-tree-title-height": "var(--cw-control-height-sm)",
  "--cw-tree-node-hover-bg": "var(--cw-control-item-bg-hover)",
  "--cw-tree-node-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-tree-directory-node-selected-color": "var(--cw-color-text-light-solid)",
  "--cw-tree-directory-node-selected-bg": "var(--cw-color-primary)",
  "--cw-tree-select-title-height": "var(--cw-control-height-sm)",
  "--cw-tree-select-node-hover-bg": "var(--cw-control-item-bg-hover)",
  "--cw-tree-select-node-selected-bg": "var(--cw-control-item-bg-active)",
  "--cw-upload-actions-color": "var(--cw-color-text-description)",
};
